language: python
python:
- '3.6'
script:
- python -m unittest discover -v
deploy:
  provider: pypi
  user: "mathiasbrito"
  password:
    secure: "GMBLuVk7xHp3e3J9AR6CQ9P+ea7HTpGUFK/SkLZkIYXFMdToQzayPq9xZvXJ/T+fuPNzKlmzaCQr2L/jYPQHUEWUaLXQXhsng8AObTCv8l3c+QTOiZoYnpwdtEiodnD6sEYJPo5WuDPbqMnMvhWTlSBDKk1TlKSd8PSC1Jz3M9+p/FWqbdFv5teHx+AnI0zmiG7ysZn6hHNZPIyXWbn9D3C0wQF5TgeYnDC6IIILHsXz363x/+zjZzuyMU6S3YVN8wnauT1YCRLh+NIDS8RdSqxSKuDykDDk8JaoNc3WexaK2gAu1iDO4JslGXHxVDEpKruJ30QkMW8SyaCO8l1sdmI8/1bJ28ev3pcpscUs/t/zq2Fw0aaBUq0StAUDdtf385lWGLqVQ5jaGXtyOWczJYPYjdb87YVKOKE++TXAWVRrsRG4NfeabL8874brDb2XcZHl/1GulBTpEtHK6Z2t1ct4FXrJQqow5Ru5sOBng4GD7UkGKpd/05aI2Zcb4KYUlVpgf2AjhIuVQgIOavFcBjvsgix6tP3vPFcciZQgLiZNKvM25A2U67qJ2PT2LX8qoRI6mV1aLy46hH6apm9sQEhJsOiiXHVa1yuEDaMTUSB3JfYKaXI+m27xDo0S97JnHhUXQ132ov5TREqmi9Q3MTbmpYtlbaXw4VD2x+1IWuU="
  on:
    branch: master
