language: python
python:
- '3.6'
script:
- python -m unittest discover -v
deploy:
  provider: pypi
  user: mathiasbrito
  password:
    secure: HbDlHn/4y1TrulU6pUy8kWISFOmhf4sYligkD/+ESg5abkS00uHJPQ1RwbP6OSpnzd4wjuXnGRwGP6WSmxikt7vO7zBKBWfKhM1erKFXvLq5HXa61gqvk7A0VuMYkp6iE/GQxJuV72XMNss+kCRDI8M+/zTIdRsWKiPciL8g+fVtA4D8Z9WRrTG/YJsQjUKU5OiDPHKMsBo+DHWX37APGldYuWdugt9nOXd7ITFhJnVvYLYkO7F4EWOGlfBfBmvRlafG9XVbialMcHcE4xVUxitbu6nkZVWq77gcfeQWKcZ5xX4Bz49McD3gISQiMQaOemarCrPuofbuAU/zbi3sBFNqhk7f6i+lRLwamDRatofx7AMhT3mp4BUgSIsGQ/0ftUim56vkRTM3KUgt23+u3QjGmctkw2UApY+GUB5MULVcB2lLuuoq7OfRuQ6L8prRYm9LZVfQuTojDk4nwwDhF8XSi5o1TwJeesu0M+whzCEgKW06b7sZM0Atz5wRgn/kByEDx7WnGvGXtvMbC8jPbruvOIAVsVNzVgBKCgwt37XfUJFpniSnYjCyTf3KvPK/tZSeV/KIvS6ocBdWpL8y3/qeCGbnF1M/0SyOgLiZxl4+p75K1JoMOyyR4ObrZV9IS0JvdBoBt/c5XDfk4QbAKuTyba2CSEeaPGhQUimy7ww=
  on:
    branch: master
    python: 3.6
