language: python
python:
- '3.6'
script:
- python -m unittest discover -v
deploy:
  provider: pypi
  user: mathiasbrito
  password:
    secure: X3sJMAtRnkxBS8tjiG5UfO+B6KWuYEP8wNiPeNSnW6kTk58DXg6EYi5uJeElPc8aiOwd/6CCvkLYCo0S6GZ71wpOEfpKm09/g6D5xHLz1rBtu+9SwH4Z5Wd7ndghNwYhZCkyWPC5ZNAEtY6r2hX3zSdRsB3mHV4n4V2dBqJQAZXz5zn1WrRdz5r2tjclKvgIFopfR/7SdcF6WkP+J7DX544Tqspt+FOrcBTpg3a+R8pSA6oOs/8tmtvSL6CGmUoU8mW009SYDjQzqns/7dxhHdxPmEiaIWFkmZkRVnl1GHrU7p8MyInKlPISsaZF4TOPrJ+tX/7DJal6DIGzfn7kO9DsfXTW/g42BA8U3DngF9dFYvENLkLTEBDkmdgjeyNtYRMNtmUHovKM3MlHUrQwfyicg8IpIsYVIZgyVU43dAnBT7hSVaB1SOAJ1KXnMyI/2PHVo4Frglb+S2C2k6k2XmmX6oWkcbrbG4x8HIuNQ7GSqsPwwPIxxPG3JmJdTy0VK+kAF2YZL0ei3/mpPT1dMdqM0/SJx927yTd0osJgfkVVUadMzzOoFWbgecq6nipyLduDYSMVI4c2UJXCEy2dmP/ngWk8ZWCKonjYsEjyjq/UHUwCS1bDyTjs3EMfp6yvDPgVfGul4Lzbja0JH8MxgWi/dOPCkxjfP1KYaIlb1wI=
  on:
    branch: master
